/**
 * Markdown Exporter Service
 * Generates markdown files with YAML frontmatter
 */

import { Report, Source } from '../../types';

interface MarkdownOptions {
  includeFrontmatter?: boolean;
  includeTableOfContents?: boolean;
  includeSources?: boolean;
  includeMetadata?: boolean;
  headingStyle?: 'atx' | 'setext';  // # vs underline
  codeBlockStyle?: 'fenced' | 'indented';
}

export class MarkdownExporter {
  private readonly defaultOptions: MarkdownOptions = {
    includeFrontmatter: true,
    includeTableOfContents: true,
    includeSources: true,
    includeMetadata: true,
    headingStyle: 'atx',
    codeBlockStyle: 'fenced',
  };

  /**
   * Generate markdown from report
   */
  generateMarkdown(report: Report, options: MarkdownOptions = {}): string {
    const opts = { ...this.defaultOptions, ...options };
    const lines: string[] = [];

    // YAML Frontmatter
    if (opts.includeFrontmatter) {
      lines.push(...this.generateFrontmatter(report));
    }

    // Title
    lines.push(this.heading(report.title, 1, opts.headingStyle));
    lines.push('');

    // Metadata block
    if (opts.includeMetadata) {
      lines.push(...this.generateMetadataBlock(report));
    }

    // Executive Summary
    if (report.summary) {
      lines.push(this.heading('Executive Summary', 2, opts.headingStyle));
      lines.push('');
      lines.push(`> ${report.summary.split('\n').join('\n> ')}`);
      lines.push('');
    }

    // Table of Contents
    if (opts.includeTableOfContents && report.sections?.length) {
      lines.push(...this.generateTableOfContents(report));
    }

    // Main Content Sections
    if (report.sections?.length) {
      report.sections.forEach((section, index) => {
        lines.push(this.heading(section.title || `Section ${index + 1}`, 2, opts.headingStyle));
        lines.push('');
        lines.push(this.formatContent(section.content, opts));
        lines.push('');

        // Handle subsections
        if (section.subsections?.length) {
          section.subsections.forEach((subsection: { title: string; content: string }) => {
            lines.push(this.heading(subsection.title, 3, opts.headingStyle));
            lines.push('');
            lines.push(this.formatContent(subsection.content, opts));
            lines.push('');
          });
        }

        // Handle tables
        if (section.tables?.length) {
          section.tables.forEach((table: { title?: string; headers: string[]; rows: string[][] }) => {
            if (table.title) {
              lines.push(`**${table.title}**`);
              lines.push('');
            }
            lines.push(this.generateTable(table.headers, table.rows));
            lines.push('');
          });
        }

        // Handle code blocks
        if (section.codeBlocks?.length) {
          section.codeBlocks.forEach((block: { language?: string; code: string; caption?: string }) => {
            lines.push(this.generateCodeBlock(block.code, block.language, opts));
            if (block.caption) {
              lines.push(`*${block.caption}*`);
            }
            lines.push('');
          });
        }
      });
    }

    // Key Findings
    if (report.keyFindings?.length) {
      lines.push(this.heading('Key Findings', 2, opts.headingStyle));
      lines.push('');
      report.keyFindings.forEach((finding, index) => {
        lines.push(`${index + 1}. ${finding}`);
      });
      lines.push('');
    }

    // Recommendations
    if (report.recommendations?.length) {
      lines.push(this.heading('Recommendations', 2, opts.headingStyle));
      lines.push('');
      report.recommendations.forEach((rec) => {
        lines.push(`- ${rec}`);
      });
      lines.push('');
    }

    // Sources/Citations
    if (opts.includeSources && report.sources?.length) {
      lines.push(...this.generateSourcesSection(report.sources));
    }

    // Footer
    lines.push('---');
    lines.push('');
    lines.push(`*Generated by [InnovateHub Research](https://innovatehub.ph) on ${new Date(report.createdAt).toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })}*`);

    return lines.join('\n');
  }

  /**
   * Generate YAML frontmatter
   */
  private generateFrontmatter(report: Report): string[] {
    const lines: string[] = ['---'];

    lines.push(`title: "${this.escapeYaml(report.title)}"`);
    lines.push(`id: ${report.id}`);
    lines.push(`query: "${this.escapeYaml(report.query)}"`);
    lines.push(`created: ${new Date(report.createdAt).toISOString()}`);
    
    if (report.updatedAt) {
      lines.push(`updated: ${new Date(report.updatedAt).toISOString()}`);
    }

    lines.push(`status: ${report.status}`);
    lines.push(`model: ${report.model || 'innovatehub-ai'}`);

    if (report.tags?.length) {
      lines.push('tags:');
      report.tags.forEach(tag => {
        lines.push(`  - ${tag}`);
      });
    }

    if (report.sources?.length) {
      lines.push(`sources_count: ${report.sources.length}`);
    }

    if (report.userId) {
      lines.push(`author_id: ${report.userId}`);
    }

    lines.push('generator: InnovateHub Research');
    lines.push('---');
    lines.push('');

    return lines;
  }

  /**
   * Generate metadata block (visible in document)
   */
  private generateMetadataBlock(report: Report): string[] {
    const lines: string[] = [];

    lines.push('| Property | Value |');
    lines.push('|----------|-------|');
    lines.push(`| **Report ID** | \`${report.id}\` |`);
    lines.push(`| **Query** | ${report.query} |`);
    lines.push(`| **Generated** | ${new Date(report.createdAt).toLocaleString()} |`);
    lines.push(`| **Sources** | ${report.sources?.length || 0} |`);
    lines.push(`| **Status** | ${report.status} |`);
    
    if (report.tags?.length) {
      lines.push(`| **Tags** | ${report.tags.map(t => `\`${t}\``).join(', ')} |`);
    }

    lines.push('');

    return lines;
  }

  /**
   * Generate table of contents
   */
  private generateTableOfContents(report: Report): string[] {
    const lines: string[] = [];

    lines.push('## Table of Contents');
    lines.push('');

    if (report.summary) {
      lines.push('- [Executive Summary](#executive-summary)');
    }

    report.sections?.forEach((section, index) => {
      const title = section.title || `Section ${index + 1}`;
      const anchor = this.slugify(title);
      lines.push(`- [${title}](#${anchor})`);

      // Subsections
      if (section.subsections?.length) {
        section.subsections.forEach((sub: { title: string }) => {
          const subAnchor = this.slugify(sub.title);
          lines.push(`  - [${sub.title}](#${subAnchor})`);
        });
      }
    });

    if (report.keyFindings?.length) {
      lines.push('- [Key Findings](#key-findings)');
    }

    if (report.recommendations?.length) {
      lines.push('- [Recommendations](#recommendations)');
    }

    if (report.sources?.length) {
      lines.push('- [References](#references)');
    }

    lines.push('');

    return lines;
  }

  /**
   * Generate sources/references section
   */
  private generateSourcesSection(sources: Source[]): string[] {
    const lines: string[] = [];

    lines.push('## References');
    lines.push('');

    sources.forEach((source, index) => {
      const num = index + 1;
      const title = source.title || 'Untitled Source';
      
      // Citation format
      lines.push(`${num}. **${title}**`);
      
      if (source.url) {
        lines.push(`   - URL: [${this.truncateUrl(source.url)}](${source.url})`);
      }

      if (source.snippet) {
        lines.push(`   - *"${this.truncate(source.snippet, 200)}"*`);
      }

      if (source.accessedAt) {
        lines.push(`   - Accessed: ${new Date(source.accessedAt).toLocaleDateString()}`);
      }

      if (source.reliability) {
        lines.push(`   - Reliability: ${source.reliability}`);
      }

      lines.push('');
    });

    return lines;
  }

  /**
   * Generate markdown table
   */
  private generateTable(headers: string[], rows: string[][]): string {
    const lines: string[] = [];

    // Header row
    lines.push(`| ${headers.join(' | ')} |`);
    
    // Separator row
    lines.push(`| ${headers.map(() => '---').join(' | ')} |`);
    
    // Data rows
    rows.forEach(row => {
      const escapedRow = row.map(cell => this.escapeTableCell(cell));
      lines.push(`| ${escapedRow.join(' | ')} |`);
    });

    return lines.join('\n');
  }

  /**
   * Generate code block
   */
  private generateCodeBlock(code: string, language?: string, opts?: MarkdownOptions): string {
    if (opts?.codeBlockStyle === 'indented') {
      return code.split('\n').map(line => `    ${line}`).join('\n');
    }

    const lang = language || '';
    return `\`\`\`${lang}\n${code}\n\`\`\``;
  }

  /**
   * Format content with proper markdown
   */
  private formatContent(content: string, opts: MarkdownOptions): string {
    if (!content) return '';

    // Already formatted markdown
    return content
      // Ensure proper paragraph breaks
      .replace(/\n{3,}/g, '\n\n')
      // Convert inline citations [1] to links
      .replace(/\[(\d+)\]/g, (match, num) => `[[${num}]](#ref-${num})`);
  }

  /**
   * Generate heading with specified style
   */
  private heading(text: string, level: number, style?: string): string {
    if (style === 'setext' && level <= 2) {
      const underline = level === 1 ? '=' : '-';
      return `${text}\n${underline.repeat(text.length)}`;
    }
    return `${'#'.repeat(level)} ${text}`;
  }

  /**
   * Convert text to URL-friendly slug
   */
  private slugify(text: string): string {
    return text
      .toLowerCase()
      .replace(/[^\w\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .trim();
  }

  /**
   * Escape YAML special characters
   */
  private escapeYaml(text: string): string {
    return text.replace(/"/g, '\\"').replace(/\n/g, ' ');
  }

  /**
   * Escape table cell content
   */
  private escapeTableCell(text: string): string {
    return text.replace(/\|/g, '\\|').replace(/\n/g, ' ');
  }

  /**
   * Truncate text with ellipsis
   */
  private truncate(text: string, maxLength: number): string {
    if (text.length <= maxLength) return text;
    return text.substring(0, maxLength - 3) + '...';
  }

  /**
   * Truncate URL for display
   */
  private truncateUrl(url: string): string {
    try {
      const parsed = new URL(url);
      const path = parsed.pathname.length > 30 
        ? parsed.pathname.substring(0, 27) + '...'
        : parsed.pathname;
      return `${parsed.hostname}${path}`;
    } catch {
      return this.truncate(url, 50);
    }
  }

  /**
   * Generate standalone markdown for a single section
   */
  generateSectionMarkdown(section: { title: string; content: string }, level: number = 2): string {
    const lines: string[] = [];

    lines.push(this.heading(section.title, level, 'atx'));
    lines.push('');
    lines.push(section.content);
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Generate markdown index for multiple reports
   */
  generateReportIndex(reports: Report[]): string {
    const lines: string[] = [];

    lines.push('# Research Reports Index');
    lines.push('');
    lines.push(`*Generated: ${new Date().toISOString()}*`);
    lines.push('');
    lines.push('| # | Title | Date | Status | Sources |');
    lines.push('|---|-------|------|--------|---------|');

    reports.forEach((report, index) => {
      const date = new Date(report.createdAt).toLocaleDateString();
      lines.push(
        `| ${index + 1} | [${report.title}](./reports/${report.id}.md) | ${date} | ${report.status} | ${report.sources?.length || 0} |`
      );
    });

    lines.push('');

    return lines.join('\n');
  }
}

export const markdownExporter = new MarkdownExporter();
